# Generated by Django 3.2.16 on 2022-12-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedPaid', models.IntegerField()),
                ('is_deposit', models.BooleanField()),
                ('transact_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transition', to='accounts.account')),
            ],
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
